ingress:
  hosts: "${MINSK_CORE_K8S_DEMO_DEPLOYMENTS_HOST}"
  path: "${APPLICATION_URL_PATH}"
image:
  repository: "${DOCKER_IMAGE_REPOSITORY}"
  tag: "${DOCKER_IMAGE_TAG}"
google:
  apiKey: "${MINSK_CORE_DEMO_GOOGLE_DRIVE_API_KEY}"
  clientId: "${MINSK_CORE_DEMO_GOOGLE_DRIVE_CLIENT_ID}"
github-status-deployment-link:
  github:
    user: "${GH_NAME}"
    password: "${GH_PASS}"
    project: "${GITHUB_PROJECT}"
    ref: "${CIRCLE_SHA1}"
  url: "${APPLICATION_URL}"
selfkiller:
  azureAks:
    resourceGroup: "${MINSK_CORE_K8S_AZURE_RG}"
    clusterName: "${MINSK_CORE_K8S_AZURE_NAME}"
  image:
    repository: "${DOCKER_IMAGE_REPOSITORY}"
    tag: "${DOCKER_IMAGE_TAG}"
  github:
    project: "${GITHUB_PROJECT}"
    branch: "${CIRCLE_BRANCH}"
slack-notifications:
  webhook: "${MINSK_CORE_SLACK_CI_WEBHOOK_URL}"
  github:
    user: "${CIRCLE_USERNAME}"
    project: "${GITHUB_PROJECT}"
    branch: "${CIRCLE_BRANCH}"
    ref: "${CIRCLE_SHA1}"
  ci:
    jobUrl: "${CIRCLE_BUILD_URL}"
  link:
    url: "${APPLICATION_URL}"
dockerSecret: "${IMAGE_PULL_SECRET_NAME}"
